### ISSUE TITLE
notebook.ipynb가 보이지 않습니다.

### ISSUE THREAD

**Issue by nothingness6** [wlsdml1114/DDSP-SVC-KOR#12]
안녕하세요.
디스코드 링크를 타고 들어가도 방이 보이지 않아서 여기에 질문을 남깁니다. 
거의 다 됐는데, 2. 데이터 준비 및 전처리, 학습 - 여기에서 왼쪽 파일 목록에서 notebook.ipynb 이라는 것이 보이지 않습니다. 
아나콘다 프롬프트 열고 기본 상태에서도 해보고, ddsp 가상환경 만들어놓은 곳으로 지정해서도 해보고, 프로젝트 파일인 DDSP-SVC로 지정하고 해봐도 notebook.ipynb는 보이지 않네요.
감사합니다.

**Comment by wlsdml1114** [comment]
DDSP-SVC라고 뜨는것을 보니 원본 레포지토리를 받으신게 아닌가 싶습니다.
notebook.ipynb는 제가 별도로 만든거라 DDSP-SVC-KOR로 폴더이름이 나와야합니다

**Comment by nothingness6** [comment]
> DDSP-SVC라고 뜨는것을 보니 원본 레포지토리를 받으신게 아닌가 싶습니다. notebook.ipynb는 제가 별도로 만든거라 DDSP-SVC-KOR로 폴더이름이 나와야합니다

아, 아닙니다. 받은건 DDSP-SVC-KOR인데, 폴더명을 줄이려고 뒤의 -KOR만 뺀겁니다. 처음에 명확히 명시를 했어야 했는데, 혼란을 드려 죄송합니다. 그런데, 폴더명이 변한것 하고 연관이 있나요?

**Comment by wlsdml1114** [comment]
폴더명이 변한것과는 연관이 없습니다.
다만 제 레포지토리에서 받으신게 맞으시면 jupyterlab에 들어갔을때 보여야 정상이라서 뭐가 잘못된건지 모르겠습니다..

**Comment by nothingness6** [comment]
> 폴더명이 변한것과는 연관이 없습니다. 다만 제 레포지토리에서 받으신게 맞으시면 jupyterlab에 들어갔을때 보여야 정상이라서 뭐가 잘못된건지 모르겠습니다..

다시 확인해 보니 경로명이 잘못됐었네요. 이제 notebook.ipynb가 제대로 보입니다. 그런데, 다른 문제가 생겼습니다. Output 화면에서 다음과 같은 에러가 뜹니다:
FileNotFoundError: [Errno 2] No such file or directory: 'pretrain/hubert\\config.yaml'

**Comment by wlsdml1114** [comment]
혹시 에러 전문을 올려주실 수 있나요?
어디에서 발생한 에러인지 확인해야할것 같습니다.

**Comment by nothingness6** [comment]
> 혹시 에러 전문을 올려주실 수 있나요? 어디에서 발생한 에러인지 확인해야할것 같습니다.

D:\Coding\Anaconda\envs\ddsp\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2023-05-07 13:41:00 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], line 21
      4 configures = {
      5     'model_path'            :   'pretrain/hubert/hubert-soft-0d54a1f4.pt', # 추론에 사용하고자 하는 모델, 바로위에서 학습한 모델을 가져오면댐
      6     'input'                 :   'data/train/audio/MyVoiceSample_01.wav', # 추론하고자 하는 노래파일의 위치 - 님들이 바꿔야댐 
   (...)
     17     'enhancer_adaptive_key' :   '0'
     18 }
     19 cmd = SimpleNamespace(**configures)
---> 21 inference(cmd)

File P:\DDSP-SVC-KOR\main.py:163, in inference(cmd)
    160     device = 'cuda' if torch.cuda.is_available() else 'cpu'
    162 # load ddsp model
--> 163 model, args = load_model(cmd.model_path, device=device)
    165 # load input
    166 audio, sample_rate = librosa.load(cmd.input, sr=44100)

File P:\DDSP-SVC-KOR\ddsp\vocoder.py:434, in load_model(model_path, device)
    430 def load_model(
    431         model_path,
    432         device='cpu'):
    433     config_file = os.path.join(os.path.split(model_path)[0], 'config.yaml')
--> 434     with open(config_file, "r") as config:
    435         args = yaml.safe_load(config)
    436     args = DotDict(args)

FileNotFoundError: [Errno 2] No such file or directory: 'pretrain/hubert\\config.yaml'

**Comment by wlsdml1114** [comment]
왜 model_path에 pretrain/hubert가 들어가있는거죵..
학습하신 모델이 있는 위치를 적어주셔야합니다
저같은경우 exp/combsub-test/model_best.pt 였습니다

**Comment by nothingness6** [comment]
> 왜 model_path에 pretrain/hubert가 들어가있는거죵.. 학습하신 모델이 있는 위치를 적어주셔야합니다 저같은경우 exp/combsub-test/model_best.pt 였습니다

패스가 잘못된거 였군요. 그런데, 오늘은 실행해 보니, 다른데서 오류가 나옵니다. 네임에러가 뜨네요 ㅠ.ㅠ
```
3. 학습
from train import ddsp_train
​
ddsp_train(args)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[1], line 3
      1 from train import ddsp_train
----> 3 ddsp_train(args)

NameError: name 'args' is not defined
```

**Comment by wlsdml1114** [comment]
껏다가 키면 맨 처음행을 실행시켜주셔야 args가 선언이됩니다

**Comment by nothingness6** [comment]
> 껏다가 키면 맨 처음행을 실행시켜주셔야 args가 선언이됩니다

아, 구글 콜랩이 지금 보니 쥬피터 노트북 베이스 였군요. 그렇게 생각하고 보니 첫번째 줄에서부터 에러가 뜨는걸 알아챘습니다. 분명히 ffmpeg는 다운로드 받아서 환경설정에 추가를 해줬는데, 뭐가 문제일까요?
```
D:\Coding\Anaconda\envs\ddsp\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
```
