### ISSUE TITLE
사전학습모델을 사용하지 않고 학습시켜보고싶은데 

### ISSUE THREAD

**Issue by Ly3e** [wlsdml1114/DDSP-SVC-KOR#15]
사전학습모델을 사용하지 않고 학습시켜보고싶은데 checkpoint안에있는 0102_xiaoma_pe, 0109_hifigan_bigpopcs_hop128 폴더만 삭제하고 이전과 같이 학습시키면 될까요?

**Comment by wlsdml1114** [comment]
어... 해보진않았는데 requirement가 아닌 optional이면 지워도 되지않을까요

**Comment by Ly3e** [comment]
감사합니다. 복사해두고 해봐야겠네요
