### ISSUE TITLE
두명의 가수를 훈련시킬 때

### ISSUE THREAD

**Issue by 2018161062Jiseong** [wlsdml1114/DDSP-SVC-KOR#17]
1번 목소리를 훈련시키다가 다른 목소리도 훈련시켜보고싶어서 2번 모델을 만드려는데
어떻게 해야 이어져서 훈련되지않고 새로운 모델로 다시 훈련을 시작할수있나요>??

**Comment by 2018161062Jiseong** [comment]
하나 더 궁금한 점이 있는데 합성 시에 diff-svc 모델에서 add to noise 같은 기능은 ddsp-svc에는 없는것인가요??

**Comment by wlsdml1114** [comment]
exp_dir과 데이터 dir 위치를 다르게 세팅한 configure를 이용해 학습하시면됩니다
