### ISSUE TITLE
결과물 뽑기 질문드려요

### ISSUE THREAD

**Issue by nodynody** [wlsdml1114/DDSP-SVC-KOR#19]
아래 오류 나는 이유 찾았습니다. 새로 지정한 모델 패스에 config.yaml 파일도 옮겨주어야 하네요. 

------------------------------------------------------------------------------------------------------------
'model_path'            :   'exp/combsub-test/model_best.pt', # 추론에 사용하고자 하는 모델, 바로위에서 학습한 모델을 가져오면댐
'input'                 :   'data/train/audio/video-0000.wav', # 추론하고자 하는 노래파일의 위치 - 님들이 바꿔야댐 
'output'                :   'output.wav',  # 결과물 파일의 위치

결과물 뽑을 때 이렇게 3부분 바꿔야 되서 아래처럼 경로 바꾸고 각 경로로 폴더 만들고
그 폴더에 10만스텝에서 나온 model을 model_best.pt로 이름 바꿔서 넣었고,
input 경로인 cover 경로에도 제가 바꾸고 싶은 노래 하나 넣고 노래 이름을 test.wav 로 변경해서 넣었구요
아웃풋 경로도 아래처럼 설정하였는데

'model_path'            :   'exp/combsubtest/model_best.pt', # 추론에 사용하고자 하는 모델, 바로위에서 학습한 모델을 가져오면댐
    'input'                 :   'data/train/cover/test.wav', # 추론하고자 하는 노래파일의 위치 - 님들이 바꿔야댐 
    'output'                :   'data/train/output/output.wav',  # 결과물 파일의 위치

아래처럼 경로 인식을 못하는 에러가 나네요. 왜 그럴까요? ㅠㅠ 경로만 남기고 파일 이름을 삭제도 해보고여러가지 해봤는데 똑같네요
무엇이 문제일까요? 미리 감사드립니다.
--------------------------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[56], line 21
      4 configures = {
      5     'model_path'            :   'exp/combsubtest/model_best.pt', # 추론에 사용하고자 하는 모델, 바로위에서 학습한 모델을 가져오면댐
      6     'input'                 :   'data/train/cover/test.wav', # 추론하고자 하는 노래파일의 위치 - 님들이 바꿔야댐 
   (...)
     17     'enhancer_adaptive_key' :   '0'
     18 }
     19 cmd = SimpleNamespace(**configures)
---> 21 inference(cmd)

File ~\Downloads\DDSP-SVC-KOR-master\DDSP-SVC-KOR-master\main.py:163, in inference(cmd)
    160     device = 'cuda' if torch.cuda.is_available() else 'cpu'
    162 # load ddsp model
--> 163 model, args = load_model(cmd.model_path, device=device)
    165 # load input
    166 audio, sample_rate = librosa.load(cmd.input, sr=44100)

File ~\Downloads\DDSP-SVC-KOR-master\DDSP-SVC-KOR-master\ddsp\vocoder.py:434, in load_model(model_path, device)
    430 def load_model(
    431         model_path,
    432         device='cpu'):
    433     config_file = os.path.join(os.path.split(model_path)[0], 'config.yaml')
--> 434     with open(config_file, "r") as config:
    435         args = yaml.safe_load(config)
    436     args = DotDict(args)

FileNotFoundError: [Errno 2] No such file or directory: 'exp/combsubtest\\config.yaml'
​

**Comment by wlsdml1114** [comment]
exp/combsubtest 폴더가 없는거 아닌가요?
실제 학습에 사용했던 폴더를 넣어주시면됩니다

**Comment by nodynody** [comment]
exp/combsubtest 폴더는 제가 새로 만들어서 가장 최근의 모델 파일을 넣었는데 모델파일만 복사하고, config 파일을 안 넣었더라구요 감사합니다.

**Comment by wlsdml1114** [comment]
해당 폴더를 직접만드실 필요는 없습니다.
학습에 사용한 configure에서 exp_dir에 자동으로 생성되니, 이 것과 같은 위치를 추론할때 사용하시면 됩니다
