### ISSUE TITLE
1.2 무음제거 단계에서 오류 관련해서 에러 전문 남깁니다...!

### ISSUE THREAD

**Issue by hos765** [wlsdml1114/DDSP-SVC-KOR#20]
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
Cell In[9], line 3
      1 from sep_wav import demucs
----> 3 demucs(ORIGINAL_PATH, DEMUCS_PATH)

File ~\Desktop\DDSP-SVC-KOR-master\DDSP-SVC-KOR-master\sep_wav.py:286, in demucs(input_path, output_path)
    284 bundle = HDEMUCS_HIGH_MUSDB_PLUS
    285 model = bundle.get_model()
--> 286 model.to(device)
    287 sample_rate = bundle.sample_rate
    288 print(f"Sample rate: {sample_rate}")

File ~\anaconda3\envs\ddsp\lib\site-packages\torch\nn\modules\module.py:1145, in Module.to(self, *args, **kwargs)
   1141         return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
   1142                     non_blocking, memory_format=convert_to_format)
   1143     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
-> 1145 return self._apply(convert)

File ~\anaconda3\envs\ddsp\lib\site-packages\torch\nn\modules\module.py:797, in Module._apply(self, fn)
    795 def _apply(self, fn):
    796     for module in self.children():
--> 797         module._apply(fn)
    799     def compute_should_use_set_data(tensor, tensor_applied):
    800         if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    801             # If the new tensor has compatible tensor type as the existing tensor,
    802             # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    807             # global flag to let the user control whether they want the future
    808             # behavior of overwriting the existing tensor or not.

File ~\anaconda3\envs\ddsp\lib\site-packages\torch\nn\modules\module.py:797, in Module._apply(self, fn)
    795 def _apply(self, fn):
    796     for module in self.children():
--> 797         module._apply(fn)
    799     def compute_should_use_set_data(tensor, tensor_applied):
    800         if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    801             # If the new tensor has compatible tensor type as the existing tensor,
    802             # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    807             # global flag to let the user control whether they want the future
    808             # behavior of overwriting the existing tensor or not.

File ~\anaconda3\envs\ddsp\lib\site-packages\torch\nn\modules\module.py:797, in Module._apply(self, fn)
    795 def _apply(self, fn):
    796     for module in self.children():
--> 797         module._apply(fn)
    799     def compute_should_use_set_data(tensor, tensor_applied):
    800         if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    801             # If the new tensor has compatible tensor type as the existing tensor,
    802             # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    807             # global flag to let the user control whether they want the future
    808             # behavior of overwriting the existing tensor or not.

File ~\anaconda3\envs\ddsp\lib\site-packages\torch\nn\modules\module.py:820, in Module._apply(self, fn)
    816 # Tensors stored in modules are graph leaves, and we don't want to
    817 # track autograd history of `param_applied`, so we have to use
    818 # `with torch.no_grad():`
    819 with torch.no_grad():
--> 820     param_applied = fn(param)
    821 should_use_set_data = compute_should_use_set_data(param, param_applied)
    822 if should_use_set_data:

File ~\anaconda3\envs\ddsp\lib\site-packages\torch\nn\modules\module.py:1143, in Module.to.<locals>.convert(t)
   1140 if convert_to_format is not None and t.dim() in (4, 5):
   1141     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
   1142                 non_blocking, memory_format=convert_to_format)
-> 1143 return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.29 GiB already allocated; 0 bytes free; 5.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by hos765** [comment]
1.1 wav변환은 문제 없이 진행 되었고, 에러가 지금은 이렇게 뜹니다..!

---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
Cell In[13], line 3
      1 from sep_wav import demucs
----> 3 demucs(ORIGINAL_PATH, DEMUCS_PATH)

File ~\Desktop\DDSP-SVC-KOR-master\DDSP-SVC-KOR-master\sep_wav.py:305, in demucs(input_path, output_path)
    302 if num_channels == 1:
    303     waveform = torchaudio.functional.remix_channels(waveform, [0, 0])
--> 305 waveform.to(device)
    307 # parameters
    308 segment: int = 15

OutOfMemoryError: CUDA out of memory. Tried to allocate 1.74 GiB (GPU 0; 6.00 GiB total capacity; 4.74 GiB already allocated; 0 bytes free; 4.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by wlsdml1114** [comment]
단순히 GPU메모리가 부족해서 나타나는 현상입니다..
