### ISSUE TITLE
notebook.ipynb에 있는 파일 자르기가 뭘 하라는 건지 모르겠습니다. 

### ISSUE THREAD

**Issue by spangni** [wlsdml1114/DDSP-SVC-KOR#7]
"## 1.4 split\n",
    "preprocess/norm에 있는 노말라이즈된 데이터들을 15초 길이로 잘라서 data/train/audio에 저장"

여기 이 부분 1.4단계에서 뭘 하라는건지 모르겠습니다ㅠㅠ 직접 파일을 잘라서 저 폴더에 저장하라는 뜻인가요..?

**Comment by wlsdml1114** [comment]
1.4 의 용도가 norm안에 있는 파일들을 15초 길이로 잘라서 train/audio에 저장해준다는 뜻입니다.
norm안에 넣어두면 알아서 잘라줄거에요
